<?php

namespace AppBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository{
	
	public function getAll(){
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM actualite";
        $statement = $connexion->query($query);
		return $statement->fetchAll();
    }

    public function getNextId(){
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT AUTO_INCREMENT
			FROM information_schema.TABLES
			WHERE TABLE_SCHEMA = 'partenaire'
			AND TABLE_NAME = 'actualite'";
        $statement = $connexion->query($query);
		return $statement->fetch();
    }
}
