<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

	public function listeContact()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM contact";
        $statement = $connexion->query($query);
		return $statement->fetchAll();
    }


	public function getListeContactPartenaire($structure)
    {
		
		$connexion = $this->getEntityManager()->getConnection();

        $query="select c.id as id,c.nom as nom, c.prenom as prenom from fos_user u, contact c where structure_id=".$structure." and contact_id=c.id";
        $statement = $connexion->query($query);
        return $statement->fetchAll();
	}

	public function getContactFromId($id)
    {
        $connexion = $this->getEntityManager()->getConnection();

        $query="SELECT * FROM contact WHERE id = ".$id;
        $statement = $connexion->query($query);
        return $statement->fetch();
        
    }
	public function getContactRefOp($id)
    {
        $connexion = $this->getEntityManager()->getConnection();

        $query="SELECT c.id as id,c.nom as nom, c.prenom as prenom, c.tel as tel, u.email as email FROM contact c, fos_user u, structure s where refOp=true and u.structure_id=s.id and u.contact_id=c.id and s.id=".$id;
        $statement = $connexion->query($query);
        return $statement->fetchAll();
        
    }
}
