<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * DemandeCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeCompteRepository extends \Doctrine\ORM\EntityRepository
{

	public function listeDemande()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM demande_compte WHERE status_id != 1";
        $statement = $connexion->query($query);
		return $statement->fetchAll();
		
    }

    public function listeDemandeEnAttente()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM demande_compte WHERE status_id = 1";
        $statement = $connexion->query($query);
		return $statement->fetchAll();
		
    }

    public function listeDemandePartenaire()
    {

        $connexion = $this->getEntityManager()->getConnection();

        $query="SELECT id FROM type_compte WHERE name = 'Gestionnaire'";
        $statement = $connexion->query($query);
        $res = $statement->fetch();



        $query="SELECT * FROM demande_compte WHERE status_id != 1 AND type_id != ".$res['id'];
        $statement = $connexion->query($query);
        return $statement->fetchAll();
        
    }

    public function listeDemandeGestionnaire()
    {
        $connexion = $this->getEntityManager()->getConnection();

        $query="SELECT id FROM type_compte WHERE name = 'Gestionnaire'";
        $statement = $connexion->query($query);
        $res = $statement->fetch();



        $query="SELECT * FROM demande_compte WHERE status_id != 1 AND type_id = ".$res['id'];
        $statement = $connexion->query($query);
        return $statement->fetchAll();
        
    }


    public function getDemandeFromId($id)
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM demande_compte WHERE id = ".$id;
        $statement = $connexion->query($query);
		return $statement->fetchAll();
		
    }

    public function getDemandeFromMail($mail)
    {
        $connexion = $this->getEntityManager()->getConnection();

        $query="SELECT * FROM demande_compte WHERE mail = ".$id;
        $statement = $connexion->query($query);
        return $statement->fetch();
        
    }
}
