<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * DemandeStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeStatusRepository extends \Doctrine\ORM\EntityRepository
{

	public function listeStatus()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM demande_status";
        $statement = $connexion->query($query);
        //dump($statement);
		return $statement->fetchAll();
		
    }
}
