<?php

namespace AppBundle\Repository;

/**
 * faq_questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faq_questionRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getQuestions() {
        $connexion=$this->getEntityManager()->getConnection();
        $sql = "select question, date_question, theme, q.faqtheme_id,  s.nom as nomStructure, p.id as pid, q.id as qid from faq_question q, faq_theme t, fos_user p, structure s where q.faqtheme_id=t.id and p.structure_id=s.id and structure_id=s.id and p.id=q.questionpartenaire_id and reponse is null order by theme";
        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
	
	public function getQuestionsFAQ($theme) {
        $connexion=$this->getEntityManager()->getConnection();
		//select question_reformule, reponse_reformule 

        $sql = "select theme, question_reformule, reponse_reformule from faq_question q, faq_theme t where dans_faq='O' and path='".$theme."' and faqtheme_id=t.id order by date_faq desc";
        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
	
	public function getReponsePourPartenaire($id_partenaire) {
        $connexion=$this->getEntityManager()->getConnection();
        $sql = "select date_question, theme, question, reponse, date_reponse from faq_question q, faq_theme t where questionpartenaire_id=".$id_partenaire." and q.faqtheme_id=t.id order by date_question desc";

        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
	
	public function getTouteLaFAQ() {
        $connexion=$this->getEntityManager()->getConnection();
        $sql = "select q.id as id, theme, question_reformule, reponse_reformule, date_faq from faq_question q, faq_theme t where dans_faq='O' and q.faqtheme_id=t.id order by theme, date_faq desc";
        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
	
}
