<?php

namespace AppBundle\Repository;

/**
 * faq_themeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class faq_themeRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getTheme ()
	{
		$connexion = $this->getEntityManager()->getConnection();

        $sql = "select distinct id, theme from faq_theme order by id ";

        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
}
