<?php

namespace AppBundle\Repository;

/**
 * informationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class informationRepository extends \Doctrine\ORM\EntityRepository{
	
	public function getByRoute($url){
		$connexion=$this->getEntityManager()->getConnection();
        $sql = "SELECT id, text, titre, urlPath FROM information where urlPath='".$url."'";
        $statement = $connexion->query($sql);
        return $statement->fetch();
	}
}
