<?php

namespace AppBundle\Repository;

/**
 * offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offreRepository extends \Doctrine\ORM\EntityRepository
{
	public function getListe() {
        $connexion=$this->getEntityManager()->getConnection();
        $sql = " SELECT id,nom_offre,dateCreation,dateFin,effacer,description from offre WHERE effacer=false";
        $statement = $connexion->query($sql);
        return $statement->fetchAll();
	}
    
    public function getById($id){
        $connexion=$this->getEntityManager()->getConnection();
        $sql = " SELECT id,nom_offre,dateCreation,dateFin,effacer,description from offre where id=$id";
        $statement = $connexion->query($sql);
        return $statement->fetch();
    }
    
	public function updateByEffacer($id,$effacer){
        $connexion = $this->getEntityManager()->getConnection();
		$sql = "UPDATE offre SET effacer=$effacer where id=$id";
        $statement = $connexion->query($sql);
        return $statement->execute();
    }
	
}
