<?php

namespace AppBundle\Repository;

/**
 * partenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class partenaireRepository extends \Doctrine\ORM\EntityRepository
{
	    public function getPartenaire($id) {
        $connexion=$this->getEntityManager()->getConnection();
        $sql = " SELECT id,nom,prenom,tel,mail,designation from partenaire WHERE id=".$id;
        $statement = $connexion->query($sql);
        //dump($sql);
        return $statement->fetch();
	}
}
