<?php

namespace AppBundle\Repository;

/**
 * TypeContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContactRepository extends \Doctrine\ORM\EntityRepository
{
	
}
