<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TypeCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompteRepository extends \Doctrine\ORM\EntityRepository
{

	public function listeType()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT * FROM type_compte";
        $statement = $connexion->query($query);
        //dump($statement);
		return $statement->fetchAll();
		
    }

    public function getIdGestionnaire()
    {
		$connexion = $this->getEntityManager()->getConnection();

		$query="SELECT id FROM type_compte WHERE name = 'Gestionnaire'";
        $statement = $connexion->query($query);
		return $statement->fetch();
    }
}
