# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded


    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt


    role_hierarchy:
        ROLE_COMMUN:       [ROLE_PARTENAIRE, ROLE_GESTIONNAIRE, ROLE_PFIDASS]
        ROLE_ADMIN:       [ROLE_USER, ROLE_PARTENAIRE, ROLE_GESTIONNAIRE, ROLE_PFIDASS]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path: inscription
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/information/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/gestionnaire/, role: ROLE_GESTIONNAIRE }
        - { path: ^/partenaire/, role: ROLE_PARTENAIRE }
        - { path: ^/commun/, role: ROLE_COMMUN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

#    app.form.change_password:
#        class: AppBundle\Form\FormChangerMdp
#        tags:
#            - { name: form.type, alias: user_change_password }

#Reset Password
#    user.resetting.form.type:
#        class: AppBundle\Form\FormReinitMdp
#        arguments: fos_user.model.user.class
#        tags:
#            - { name: form.type, alias: user_resetting }